# .coveralls.yml example configuration

# same as Ruby lib
repo_token: DVF4sjTg9ROVQBQw1oFbUuOeXkmoI39wK # should be kept secret!
service_name: travis-ci # travis-ci or travis-pro

# for php-coveralls
src_dir: src
coverage_clover: build/logs/clover.xml
json_path: build/logs/coveralls-upload.json